### ISSUE TITLE
JS heap out of memory

### ISSUE THREAD

**Issue by aruan-cuenca-emasoftware** [dilanx/craco#335]
I'm facing this error when trying to run `craco build`. The `craco start` script works fine (just takes a long time to run)
I've tried to set `--max-old-space-size=8192` after searching similar issues, but nothing changed.
My node version is 15.11.0.

![issue_craco](https://user-images.githubusercontent.com/73557853/137338053-9e41d72a-8d97-4653-b16a-ffae363858c8.GIF)

**Comment by huangt2012** [comment]
fixed this error by modifying the script like this "start": "craco --max_old_space_size=4096 start", "build": "craco --max_old_space_size=4096 build"

**Comment by huangt2012** [comment]
fixed this error by modifying the script 
 `start: "craco --max_old_space_size=4096 start"`
`build: "craco --max_old_space_size=4096 build"`

**Comment by AlmogBaku** [comment]
How's increasing the memory to 4GB considered a good solution? lol
We have a memory leak

**Comment by dilanx** [comment]
@AlmogBaku my mistake, I forgot that I said that. Regardless, I'm not sure if this is an issue with craco specifically.

You could potentially try duplicating your project, eject it from CRA, and then change the relevant ejected config files to match what you have in your craco config (like edit your webpack config to include the changes you made to webpack in your craco config). Then, use the normal `react-scripts` to start or build your app to see if the issue persists, because if it does, then it probably does not relate to craco.

**Comment by rfsbsb** [comment]
I know it's been closed for a while. One thing that helped me was disable eslint during the build process:

```
module.exports = {
  eslint: {
    enable: false
  },
...
}
``` 
Hopefully this help other people like me that ended up here :-)

**Comment by silva95gustavo** [comment]
I could only solve this issue by adding the following to `craco.config.js`:
```
  webpack: {
    // https://webpack.js.org/configuration
    configure: (config) => {

      // ....

      config.plugins
        .filter((plugin) => plugin.constructor.name === 'ForkTsCheckerWebpackPlugin')
        .forEach((plugin) => {
          plugin.options.typescript = plugin.options.typescript || {};
          plugin.options.typescript.memoryLimit = 4096;
        });

      // ....

      return config;
    },
```

This increases the memory allocated to the `ForkTsCheckerWebpackPlugin` which is used by React build script when using Typescript.

**Comment by adelphes** [comment]
```
module.exports = {
   ...
   webpack: {
    configure: (config) => {
      config.plugins
        .filter((plugin) => plugin.constructor.name === 'ForkTsCheckerWebpackPlugin')
        .forEach((plugin) => {
            plugin.options.memoryLimit = plugin.memoryLimit = 4096;
        });
      return config;
    },
}

```
