### ISSUE TITLE
Babel 7.13 compiler assumptions

### ISSUE THREAD

**Issue by hyperknot** [dilanx/craco#350]
Hi, will it be possible to use the Babel 7.13 compiler assumptions with an `assumptions` key?
https://babeljs.io/docs/en/assumptions

For example MobX [docs say](https://mobx.js.org/installation.html) the following:
```
{
    "plugins": [["@babel/plugin-proposal-class-properties", { "loose": false }]],
    // Babel >= 7.13.0 (https://babeljs.io/docs/en/assumptions)
    "assumptions": {
        "setPublicClassFields": false
    }
}
```

It'd be nice to use this syntax in CRACO.

**Comment by DronDima** [comment]
Hello, i also have issue with `assumptions`. I'm trying to use decorator inside react class component, but babel overrides it. So, from different sources([one](https://github.com/lit/lit-element/issues/234#issuecomment-427137564), [two](https://stackoverflow.com/questions/59698982/how-to-use-babel-legacy-decorators/59699245#59699245) and others) it looks like i need to add `@babel/plugin-proposal-decorators` with `legacy: true`. But [In official documentation](https://babeljs.io/docs/en/babel-plugin-proposal-decorators#note-compatibility-with-babelplugin-proposal-class-properties) they have note that we need to add `setPublicClassFields` assumption in babel config when using `legacy: true`.

**Comment by hyperknot** [comment]
@DronDima I don't think the assumption is needed as of today, as the current Babel is 7.12 in CRA.

This works for decorators:
```
module.exports = {
  babel: {
    plugins: [
      ['@babel/plugin-proposal-decorators', { legacy: true }],
      ['@babel/plugin-proposal-class-properties', { loose: false }],
    ]
  },
}
```

**Comment by hyperknot** [comment]
OK, the new CRA 5.x actually ships Babel 7.16, so we'd need these assumptions. Has anyone managed to get this right?

**Comment by hyperknot** [comment]
Not stale

**Comment by dilanx** [comment]
@hyperknot sorry for such a long delay. I've added this functionality and will release it in alpha 8. I haven't tested it, but if you'd like to ensure that it works for you as you expect once alpha 8 is out, that would be great!

**Comment by hyperknot** [comment]
I've done the upgrade to test this. It seems to be working, at least I get a warning message if I add assumptions. There are other errors with react-scripts@5.x which I won't start debugging, but the CRACO part seems to be working.

**Comment by dilanx** [comment]
Thanks @hyperknot. If the craco part seems to be working, I'll close this issue. Feel free to leave a comment if there are any problems.
