### ISSUE TITLE
Linting step causes a compilation error can't read 'ScopeType'

### ISSUE THREAD

**Issue by ghislainDeffo** [dilanx/craco#352]
![image](https://user-images.githubusercontent.com/92927993/145614319-18198f3d-7190-4ec1-82a3-03dc77fb4acd.png)
That file is re-exported in
![image](https://user-images.githubusercontent.com/92927993/145615717-ea8b60fc-50f8-422a-ad5a-5662810a140b.png)

Just running `eslint src` works just fine. Running `craco start` or `craco build` with 
```js
eslint: {
    enable: false
}
```
in the craco config

**Comment by RichardEG95** [comment]
I'm experienceing the same issue. Disabling the eslint worked. 
Thank you

**Comment by dilanx** [comment]
Is this still an issue?
