### ISSUE TITLE
craco always returning exit code 0

### ISSUE THREAD

**Issue by fxsalazar** [dilanx/craco#366]
When running `npx craco build` with a build error, it is always returning exit code 0.
If I change it to `npx react-scripts build` it correctly gives me the exit error code 1.

Tested on my local machine and discovered on a CircleCI  run.

Am I the only one bothered by this?

**Comment by luffy84217** [comment]
@fxsalazar Could you provide your CRA version?

**Comment by fxsalazar** [comment]
```
react-scripts v4.0.3
craco v6.4.2
```

As any other info, I can say that my specific build error was with a missing module in the lock file, but I don't think it's relevant for this issue.

**Comment by stevenewald** [comment]
Cannot replicate with details provided
