### ISSUE TITLE
Cant configure webpack to bundle css from node_module/dist

### ISSUE THREAD

**Issue by leon-up9** [dilanx/craco#397]
how to load css files from a lib installed with npm and exist in node_module/dist.
I would expected that when using a component from that lib (witch was installed) it would load the css files that were imported and used inside that component.

can i do it with craco.config.js?

**Comment by dilanx** [comment]
A plugin for webpack like [css-loader](https://github.com/webpack-contrib/css-loader) will probably work well here. However, it requires webpack 5, which we don't fully support yet. I'm working on it though!
