### ISSUE TITLE
Unable to run node debugger with craco test

### ISSUE THREAD

**Issue by bring-shrubbery** [dilanx/craco#401]
## Problem

When trying to run node debugger with craco, it only records the `craco.js` or `jest.js` file, not the tests themselves.

## Expected behaviour

When running the node debugger like described in this [troubleshooting guide](https://jestjs.io/docs/troubleshooting), I expect for Chrome profiler to record the performance and memory of the test runs.

## Steps to reproduce

1. Clone a repo that uses Craco
2. Try running following command and opening debugger in chrome: `node --inspect-brk node_modules/@craco/craco/bin/jest.js --runInBand`
3. Open Chrome DevTools and try recording the test runs.

**Comment by zhang-li-80** [comment]
Same here.

The issue with craco is that it spawns a new node process, which stops the debugger from working.

The workaround is to run the `jest` command directly.

**Comment by bring-shrubbery** [comment]
@dilanx Does this mean that we can now run node debugger on craco? Running jest directly does not work for me 🤷‍♀️

**Comment by dilanx** [comment]
Ah sorry @bring-shrubbery, not yet. I assumed running `jest` directly solved the issue (and there was no further activity here after that was posted), so I closed the issue. I'll reopen it for now though and look into it when I get the chance.

**Comment by victoriahu** [comment]
@bring-shrubbery Have you tried 

```
"scripts": {
    "test:debug": "react-scripts --inspect-brk test --runInBand --no-cache"
  }
```

from the CRA documentation [here](https://create-react-app.dev/docs/debugging-tests/) ?

**Comment by bring-shrubbery** [comment]
@victoriahu I'm no longer working on the team that used this craco setup, but they had a custom webpack config which made it impossible to simply debug the app with the `react-scripts`. I had to eject the app entirely on a separate branch, and debug it like that.

Having said that, if someone else is looking to debug a craco app using node debugger you can do so by:

1. Create a new branch
2. Eject the app using `react-scripts eject`
3. Run the debugger as if it's a regular `react-scripts` app
4. Find the issue
5. Reject all changes and update the issue in your regular code.
