### ISSUE TITLE
LOOKING FOR A NEW TEAM TO LEAD CRACO

### ISSUE THREAD

**Issue by patricklafrance** [dilanx/craco#415]
After a few years, GSoft decided to stop maintaining CRACO. I personnally have a new role and I don't have the time (or motivation) to contribute anymore. Since we are short staff, the management at GSoft won't assign anyone on this project.

Instead of killing the project, I would prefer to transfer the ownership to a new team since it's still widely used and the CRA 5 support is almost done.

If you are interested, manifest yourself in this issue.

**Comment by Codex-** [comment]
It's always hard when life and priorities change tracks, thanks for all the contributions!

Would you be looking for a group specifically or motivated individuals?

**Comment by patricklafrance** [comment]
I am fine with both @Codex-

A team or a motivated individual who will be the new owner of the repo and take the lead.

**Comment by akachicon** [comment]
@patricklafrance 
First of all, thanks for the great job during all these years! Can you please describe the scope of work you see necessary to release cra5 support?

**Comment by patricklafrance** [comment]
Hey @akachicon 

The [utility functions](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#utility-functions) have to adapted to work with Webpack 5. I think it requires a full redesign.

Otherwise it's mostly about testing different use cases. I haven't test much CRACO with CRA5 so there might be other things like lesser used features that are broken.

From the comments in the issues there doesn't seem to have many problems thought.

**Comment by XzaR90** [comment]
In mean time are there any alternatives library that support CRA 5?

**Comment by mattsputnikdigital** [comment]
@XzaR90 https://www.npmjs.com/package/react-app-rewired I believe is an alternative. I had it generating a CSP but couldn't get SASS features to work so I need to look into it further. Craco is so much easier...

**Comment by patricklafrance** [comment]
@XzaR90 @mattsputnikdigital please create a new issue to talk about matters not related to finding new maintainers for craco.

Thank you

**Comment by dilanx** [comment]
Has a new maintainer been found, or not yet?

**Comment by dilanx** [comment]
Thanks for your response @patricklafrance

Is there a good method I could use to contact you directly?

**Comment by dilanx** [comment]
Thanks, @patricklafrance. It says that you have incoming DMs from anyone disabled. You can message me on [Twitter](https://twitter.com/dilans4k) if you'd like.

**Comment by dilanx** [comment]
:smile:
