### ISSUE TITLE
extends-post-css-plugins example doesn't work

### ISSUE THREAD

**Issue by AndrejGajdos** [dilanx/craco#417]
I tried [this example](https://github.com/gsoft-inc/craco/blob/master/recipes/extends-post-css-plugins/craco.config.js) with CRA v5, but it doesn't work. You can check sample repo [here](https://github.com/AndrejGajdos/craco-test/blob/main/craco.config.js) where I tried to use `postcss-color-rgb`. You can run the project, but [the css file](https://github.com/AndrejGajdos/craco-test/blob/9becc9871618431e42307f8ff109e6577b5f220a/src/App.css#L17) is not processed.

At first I tried craco [6.4.3](https://www.npmjs.com/package/@craco/craco/v/6.4.3), but I was getting [this](https://stackoverflow.com/questions/70403417/typeerror-match-loader-options-plugins-is-not-a-function) issue. When I replaced `postcss` with `postOptions`, I didn't get any errors, but the css is not processed. Then I came across [this](https://github.com/facebook/create-react-app/issues/11777#issuecomment-1086940832) suggestion and tried both `postcss` and `postOptions`, but the css is still not processed.

**Comment by dbgordon09** [comment]
Can confirm I am also dealing with this issue. It seems that craco is not correctly extending `postcss`.

Will post here if I manage to come up with a work around, please do the same 😃

**Comment by SophieAnn** [comment]
Does someone has an update or a workaround for this? I am struggeling with the same problem and can't use `postcss`, always getting a compile failing error TypeError: plugin is not a function at new Promise (<anonymous>)).
I am using the latest craco version. I can't update any other versions, I am using:
`"react-scripts": "^4.0.3"`
`"webpack": "4.44.2"`

**Comment by dilanx** [comment]
@AndrejGajdos I just tested your example repo with CRA 5 using the latest craco 7 alpha and it worked as expected. I tried changing the background color in the `App.css` file and it updated properly. Are you able to reproduce the issue using the latest alpha of craco 7?

@dbgordon09 is this still an issue for you as well?

@SophieAnn what version of craco are you using?
