### ISSUE TITLE
How to use thread-loader in craco?

### ISSUE THREAD

**Issue by Kujo-Jotaro-AAAAA** [dilanx/craco#420]
How to use thread-loader in craco?
```js
module: {
      rules: [
        {
          test: /.js$/,
          include: path.resolve(__dirname, '../src'),
          use: [
            // 'babel-loader',
            {
              loader: 'thread-loader',
              options: {
                workers: 3,
              },
            },
          ],
        },
      ],
    }
```
But,It won't work

error message: Error: Can't find a 'oneOf' rule under module.rules in the production webpack config!

**Comment by dilanx** [comment]
@Kujo-Jotaro-AAAAA I might some more context to try and recreate this issue. Can you create a demo repo that has this issue, or maybe share your craco config and package.json?
