### ISSUE TITLE
7.0.0-alpha.6 - a babel plugin doesn't work

### ISSUE THREAD

**Issue by deenns** [dilanx/craco#433]
I use only one babel plugin: 

```
babel: {
    plugins: ["babel-plugin-styled-components"]
}
```
It's required to convert `<div css={"flex: 1 1 auto;"}>something</div>` into styled components.

And it seems to not work or work incorrectly, because all the `css` props aren't processed and just added as attributes to the DOM elements. With `alpha.3` version it works as expected.

**Comment by bigbali** [comment]
Hey, I had a similar issue, where module.exports.babel.loaderOptions would be ignored while using '7.0.0-alpha.6'. Downgraded to '7.0.0-alpha.3' and it seems to work.

**Comment by dilanx** [comment]
This should now be fixed in alpha 7, sorry!
