### ISSUE TITLE
how to use REACT_APP_XXXX Env from create react app?

### ISSUE THREAD

**Issue by tal-rofe** [dilanx/craco#437]
with CRA I used an ENV : |
```
REACT_APP_BACKEND_URL="http://localhost:3000"
```

However when using CRACO this env variable seems to be undefined.

How can I use envs then?

**Comment by dilanx** [comment]
I just tested it and it looks like all `REACT_APP_` env variables are still valid when using craco. How are you loading your env variables?

**Comment by tal-rofe** [comment]
@dilanx 
I just have .env.development file in root folder

**Comment by dilanx** [comment]
Sorry for the delay. I just tested it (on `7.0.0-alpha.7`) and it worked as expected for me. Do you think you could share more info that I could potentially use to try and recreate your issue? A demo repo would work.

I created a `.env.development` file in the root folder of a project with craco installed and included a variable called `REACT_APP_BACKEND_URL` like you have. It was included in the project as expected when I started the dev server.
