### ISSUE TITLE
how to use an existing jest.config.js to be merged with craco configuration ?

### ISSUE THREAD

**Issue by Maikel-Nait** [dilanx/craco#438]
Hi. We are using craco with custom Jest configuration and it works perfectly fine.
However, it seems we can only configure jest properties inside the **craco.config.js** file. The configuration here gets merged with the default configuration provided by CRA as expected (or with our own Jest plugin, if we provide one)

However, if we try having a **jest.config.js** with some custom jest configuration (instead of the default options provided by CRA), this doesn't seem to work at all.

So the basic question is :  when using craco ... does it make sense to use a **jest.config.js** ?  Or all the jest configuration should be done on the **craco.config.js** (and jest override plugins) ?

We also tried to ensure the **jest.config.js** was being used, by passing the "-- --config=jest.config.js"  arguments to the "test" script, but then we run into all shorts of issues, apparently because there's already another "--config" argument set by craco...

Thanks in advance !

**Comment by dilanx** [comment]
As far as I know, CRA prevents you from modifying certain configuration files unless you eject. The point of craco is to allow config modifications without ejecting, but only config properties in `craco.config.js` will be considered by craco. Modifying your jest settings within the craco config should be sufficient! If you'd like to override the default options provided by CRA, that should be possible by simply putting those options and their new values within the craco config.

**Comment by Maikel-Nait** [comment]
Thanks for confirmation! We can close the issue
