### ISSUE TITLE
Remove .map files from build folder

### ISSUE THREAD

**Issue by ashotosipyan** [dilanx/craco#439]
Hi,

I'm trying to get rid of the map files after `craco build` command, but unfortunately nothing worked for me, maybe there is a config for this? I can't find anything in docs, thank you!

**Comment by dilanx** [comment]
Setting up your craco config like below should do the trick. I plan on reworking the documentation soon so maybe I can add this as a recipe so others can refer to it as well.

```js
/* craco.config.js */

module.exports = {
  webpack: {
    configure: (webpackConfig) => {
      delete webpackConfig.devtool;
      return webpackConfig;
    }
  }
}
```

**Comment by ashotosipyan** [comment]
Thank you @dilanx, that's worked!
