### ISSUE TITLE
[Help] How to use CRACO with yarnPnp or pnpm?

### ISSUE THREAD

**Issue by xyy94813** [dilanx/craco#446]
I am trying to use `yarnPnp` or `pnpm` in my project.
But, I ran into a lot of problems with undeclared modules that are declared in `react-scripts`.

For example:
```
Cannot find module 'postcss'
```

```
Error: Your application tried to access `eslint-config-react-app`, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

The easiest way is to re-depend on these modules in my project.
it is contrary to my original intention of using `craco`

Can I go against the design principles of `yarnPnp` and `pnpm` in certain scenarios
Is there any workaround to fix it?

**Comment by dilanx** [comment]
@xyy94813 can you share your package.json (mainly the dependency lists)?
