### ISSUE TITLE
After implementing craco my build failed in the server

### ISSUE THREAD

**Issue by snairsumith** [dilanx/craco#451]
Any idea about this issues. I am using craco version 5.8.0
<img width="1350" alt="Screenshot 2022-09-05 at 5 11 15 PM" src="https://user-images.githubusercontent.com/8740519/188440869-bf154d8c-5e91-445f-99a3-ddd5acc35cbd.png">

**Comment by dilanx** [comment]
@snairsumith I'm not sure if this has anything to do with craco itself. It could either be something in your configuration or something else entirely. Could you share your dependency list and your craco config?
