### ISSUE TITLE
[Help] Close compiler at build end

### ISSUE THREAD

**Issue by shemayas** [dilanx/craco#452]
I'm trying to use [Webpack cache option](https://webpack.js.org/configuration/cache/#cache) and it's not working due to an issue in CRA that is [described here](https://github.com/facebook/create-react-app/pull/12391)

In essence the problem is that `compile.close()` is not called 

Is there an option to add the needed `compiler.close()` call with craco?

**Comment by dilanx** [comment]
@shemayas unfortunately, there is not, since craco just injects the config modifications and then runs CRA's build script (without directly modifying its build script). This would require modifying `react-scripts`'s source code directly.
