### ISSUE TITLE
create-react-app@5.0.1 create project installing dependency fail

### ISSUE THREAD

**Issue by freeshineit** [dilanx/craco#455]
Run npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-clipboardjs-copy@2.0.0
npm ERR! Found: react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   dev react-scripts@"5.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-scripts@"^[4](https://github.com/freeshineit/react-clipboardjs-copy/actions/runs/3168865278/jobs/5160369880#step:4:5).0.0" from @craco/craco@6.4.[5](https://github.com/freeshineit/react-clipboardjs-copy/actions/runs/3168865278/jobs/5160369880#step:4:6)
npm ERR! node_modules/@craco/craco
npm ERR!   dev @craco/craco@"^[6](https://github.com/freeshineit/react-clipboardjs-copy/actions/runs/3168865278/jobs/5160369880#step:4:7).4.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-10-02T14_04_01_[8](https://github.com/freeshineit/react-clipboardjs-copy/actions/runs/3168865278/jobs/5160369880#step:4:9)[9](https://github.com/freeshineit/react-clipboardjs-copy/actions/runs/3168865278/jobs/5160369880#step:4:10)0Z-debug-0.log

**Comment by dilanx** [comment]
You need to use craco 7 for CRA 5 support. A stable release is not out yet but you can use the latest alpha build (`npm i @craco/craco@alpha`). This will also be documented clearly once the release is out.
