### ISSUE TITLE
Craco with jest 27 createTransformer and _cracoConfig undefined with react-scripts 5

### ISSUE THREAD

**Issue by kelbyers** [dilanx/craco#462]
I'm using react-scripts 5.0.1, and get this error when running `craco test`:

```
TypeError: Cannot read properties of undefined (reading '_cracoConfig')
```

The same changes mentioned in #425 fixed the issue, but updating to craco 6.4.5 did not resolve the issue.

**Comment by dilanx** [comment]
What version of craco are you using?

**Comment by kelbyers** [comment]
I tried both 6.4.3 and 6.4.5.

**Comment by dilanx** [comment]
Try using craco 7 (it just moved from alpha to latest) because craco 6 does not support CRA 5.

**Comment by kelbyers** [comment]
I'll give it a try tomorrow. I'm also using `craco-antd`, which also uses `craco-less`, and those set their peer dependencies to exactly version 6.4.3. I can configure my environment to use craco 7 instead, though.

**Comment by kelbyers** [comment]
craco 7 did resolve my issues. Thanks! It was still a beta when I looked earlier, and I didn't think to check if it had been released when I ran into the issue.
