### ISSUE TITLE
Discussions section

### ISSUE THREAD

**Issue by criszz77** [dilanx/craco#471]
Hello!

Thank you for the new version of this module! The community has been waiting for it.

**The problem:**
I'm the author of [luna](https://github.com/criszz77/luna) and we're using react-scripts to create a React Native app that runs on iOS, Android and web concurrently. We've switching to react-app-rewired since CRACO did not work with CRA5, but we're here now, and we want to come back to CRACO. However, it seems that simply using our last CRACO setup does not work anymore: https://github.com/criszz77/luna/pull/54

**The solution:**
 I would love to have a `Discussions` sections where the community can engage in helping each other and share ideas about CRACO. :)

**Comment by dilanx** [comment]
I'm not sure what you mean. Are you talking about the discussions feature on GitHub?

**Comment by criszz77** [comment]
Indeed, yes, thank you! Really appreciate it. I guess it's better to have a Discussions sections rather than opening issues to ask for help. Cheers
